export const casbinPolicy = `
p, role:staff, /api/v1/user, read
p, role:staff, /api/v1/user/:id, read
p, role:staff, /api/v1/school, read
p, role:staff, /api/v1/school/:id, read
p, role:staff, /api/v1/course, read
p, role:staff, /api/v1/course/:id, read
p, role:staff, /api/v1/course/schedule, read
p, role:staff, /api/v1/student, read
p, role:staff, /api/v1/student/:id, read
p, role:staff, /api/v1/attendance, read
p, role:staff, /api/v1/attendance/:id, read
p, role:staff, /api/v1/grade-sheet, read
p, role:staff, /api/v1/grade-sheet/:id, read
p, role:staff, /api/v1/salary-base, read
p, role:staff, /api/v1/salary-base/:id, read
p, role:staff, /api/v1/dashboard/statistics, read
p, role:staff, /api/v1/attendance/statistics, read
p, role:staff, /api/v1/attendance/batch, read
p, role:staff, /api/v1/attendance/export, read
p, role:staff, /api/v1/grade-sheet/statistics, read
p, role:staff, /api/v1/grade-sheet/export, read
p, role:staff, /api/v1/student/export, read
p, role:staff, /api/v1/upload, read
p, role:staff, /api/v1/course-session, read
p, role:staff, /api/v1/course-session/:id, read
p, role:staff, /api/v1/course-session/salary-summary, read
p, role:staff, /api/v1/course-session/batch-generate, read
p, role:staff, /api/v1/health-weight, read
p, role:staff, /api/v1/health-weight, create
p, role:staff, /api/v1/health-weight/:id, read
p, role:staff, /api/v1/health-weight/:id, update
p, role:staff, /api/v1/health-weight/:id, delete
p, role:staff, /api/v1/health-weight/statistics, read
p, role:staff, /api/v1/health-weight/export, read
p, role:staff, /api/v1/health-diet, read
p, role:staff, /api/v1/health-diet, create
p, role:staff, /api/v1/health-diet/:id, read
p, role:staff, /api/v1/health-diet/:id, update
p, role:staff, /api/v1/health-diet/:id, delete
p, role:staff, /api/v1/health-diet/statistics, read
p, role:staff, /api/v1/health-diet/export, read
p, role:staff, /api/v1/health-toilet, read
p, role:staff, /api/v1/health-toilet, create
p, role:staff, /api/v1/health-toilet/:id, read
p, role:staff, /api/v1/health-toilet/:id, update
p, role:staff, /api/v1/health-toilet/:id, delete
p, role:staff, /api/v1/health-toilet/statistics, read
p, role:staff, /api/v1/health-toilet/export, read

p, role:manager, /api/v1/user, create
p, role:manager, /api/v1/user/:id, update
p, role:manager, /api/v1/school, create
p, role:manager, /api/v1/school/:id, update
p, role:manager, /api/v1/course, create
p, role:manager, /api/v1/course/:id, update
p, role:manager, /api/v1/student, create
p, role:manager, /api/v1/student/:id, update
p, role:manager, /api/v1/attendance, create
p, role:manager, /api/v1/attendance/:id, update
p, role:manager, /api/v1/grade-sheet, create
p, role:manager, /api/v1/grade-sheet/:id, update
p, role:manager, /api/v1/salary-base, create
p, role:manager, /api/v1/salary-base/:id, update
p, role:manager, /api/v1/attendance/batch, create
p, role:manager, /api/v1/student/import, create
p, role:manager, /api/v1/upload, create
p, role:manager, /api/v1/course-session, create
p, role:manager, /api/v1/course-session/:id, update
p, role:manager, /api/v1/course-session/batch-generate, create

p, role:admin, /api/v1/user, *
p, role:admin, /api/v1/user/:id, *
p, role:admin, /api/v1/school, *
p, role:admin, /api/v1/school/:id, *
p, role:admin, /api/v1/course, *
p, role:admin, /api/v1/course/:id, *
p, role:admin, /api/v1/course/schedule, *
p, role:admin, /api/v1/student, *
p, role:admin, /api/v1/student/:id, *
p, role:admin, /api/v1/attendance, *
p, role:admin, /api/v1/attendance/:id, *
p, role:admin, /api/v1/grade-sheet, *
p, role:admin, /api/v1/grade-sheet/:id, *
p, role:admin, /api/v1/salary-base, *
p, role:admin, /api/v1/salary-base/:id, *
p, role:admin, /api/v1/dashboard/statistics, *
p, role:admin, /api/v1/attendance/statistics, *
p, role:admin, /api/v1/attendance/batch, *
p, role:admin, /api/v1/attendance/export, *
p, role:admin, /api/v1/grade-sheet/statistics, *
p, role:admin, /api/v1/grade-sheet/export, *
p, role:admin, /api/v1/student/export, *
p, role:admin, /api/v1/student/import, *
p, role:admin, /api/v1/upload, *
p, role:admin, /api/v1/upload/:publicId, *
p, role:admin, /api/v1/course-session, *
p, role:admin, /api/v1/course-session/:id, *
p, role:admin, /api/v1/course-session/salary-summary, *
p, role:admin, /api/v1/course-session/batch-generate, *
p, role:admin, /api/v1/course-session/recalculate-salaries, *
p, role:admin, /api/v1/audit-log, *
p, role:admin, /api/v1/audit-log/:id, *
p, role:admin, /api/v1/health-weight, *
p, role:admin, /api/v1/health-weight/:id, *
p, role:admin, /api/v1/health-weight/statistics, *
p, role:admin, /api/v1/health-weight/export, *
p, role:admin, /api/v1/health-diet, *
p, role:admin, /api/v1/health-diet/:id, *
p, role:admin, /api/v1/health-diet/statistics, *
p, role:admin, /api/v1/health-diet/export, *
p, role:admin, /api/v1/health-toilet, *
p, role:admin, /api/v1/health-toilet/:id, *
p, role:admin, /api/v1/health-toilet/statistics, *
p, role:admin, /api/v1/health-toilet/export, *

g, role:admin, role:manager
g, role:manager, role:staff`;
