export const casbinPolicy = `
p, role:staff, /api/v1/user, read
p, role:staff, /api/v1/user/:id, read
p, role:staff, /api/v1/school, read
p, role:staff, /api/v1/school/:id, read
p, role:staff, /api/v1/course, read
p, role:staff, /api/v1/course/:id, read
p, role:staff, /api/v1/student, read
p, role:staff, /api/v1/student/:id, read
p, role:staff, /api/v1/attendance, read
p, role:staff, /api/v1/attendance/:id, read
p, role:staff, /api/v1/grade-sheet, read
p, role:staff, /api/v1/grade-sheet/:id, read
p, role:staff, /api/v1/blog, read
p, role:staff, /api/v1/blog/:id, read
p, role:staff, /api/v1/banner, read
p, role:staff, /api/v1/banner/:id, read
p, role:staff, /api/v1/video, read
p, role:staff, /api/v1/video/:id, read
p, role:staff, /api/v1/dashboard/statistics, read
p, role:staff, /api/v1/attendance/statistics, read
p, role:staff, /api/v1/attendance/batch, read
p, role:staff, /api/v1/attendance/export, read
p, role:staff, /api/v1/grade-sheet/statistics, read
p, role:staff, /api/v1/grade-sheet/export, read
p, role:staff, /api/v1/student/export, read
p, role:staff, /api/v1/upload, read

p, role:manager, /api/v1/user, create
p, role:manager, /api/v1/user/:id, update
p, role:manager, /api/v1/school, create
p, role:manager, /api/v1/school/:id, update
p, role:manager, /api/v1/course, create
p, role:manager, /api/v1/course/:id, update
p, role:manager, /api/v1/student, create
p, role:manager, /api/v1/student/:id, update
p, role:manager, /api/v1/attendance, create
p, role:manager, /api/v1/attendance/:id, update
p, role:manager, /api/v1/grade-sheet, create
p, role:manager, /api/v1/grade-sheet/:id, update
p, role:manager, /api/v1/blog, create
p, role:manager, /api/v1/blog/:id, update
p, role:manager, /api/v1/banner, create
p, role:manager, /api/v1/banner/:id, update
p, role:manager, /api/v1/video, create
p, role:manager, /api/v1/video/:id, update
p, role:manager, /api/v1/attendance/batch, create
p, role:manager, /api/v1/student/import, create
p, role:manager, /api/v1/upload, create

p, role:admin, /api/v1/user, *
p, role:admin, /api/v1/user/:id, *
p, role:admin, /api/v1/school, *
p, role:admin, /api/v1/school/:id, *
p, role:admin, /api/v1/course, *
p, role:admin, /api/v1/course/:id, *
p, role:admin, /api/v1/student, *
p, role:admin, /api/v1/student/:id, *
p, role:admin, /api/v1/attendance, *
p, role:admin, /api/v1/attendance/:id, *
p, role:admin, /api/v1/grade-sheet, *
p, role:admin, /api/v1/grade-sheet/:id, *
p, role:admin, /api/v1/blog, *
p, role:admin, /api/v1/blog/:id, *
p, role:admin, /api/v1/banner, *
p, role:admin, /api/v1/banner/:id, *
p, role:admin, /api/v1/video, *
p, role:admin, /api/v1/video/:id, *
p, role:admin, /api/v1/dashboard/statistics, *
p, role:admin, /api/v1/attendance/statistics, *
p, role:admin, /api/v1/attendance/batch, *
p, role:admin, /api/v1/attendance/export, *
p, role:admin, /api/v1/grade-sheet/statistics, *
p, role:admin, /api/v1/grade-sheet/export, *
p, role:admin, /api/v1/student/export, *
p, role:admin, /api/v1/student/import, *
p, role:admin, /api/v1/upload, *
p, role:admin, /api/v1/upload/:publicId, *

g, role:admin, role:manager
g, role:manager, role:staff`;
